version: "3.9"

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: movie_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - client
      - server
    restart: always

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: movie_client
    environment:
      NODE_ENV: production
    expose:
      - "3000"
    restart: always

  server:
    build:
      context: ../server
    container_name: movie_server
    environment:
      API_KEY: ${API_KEY}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
      CACHE_TYPE: ${CACHE_TYPE}
      CACHE_REDIS_URL: ${CACHE_REDIS_URL}
      PORT: 8080
    expose:
      - "8080"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:17
    container_name: movie_db
    environment:
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: movie_db
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
